#!/bin/sh
session="handover"
tmux new-session -d -s $session
tmux send-keys 'roslaunch e2e_handover e2e_handover.launch'
tmux split-window -h
tmux send-keys 'roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch'
tmux split-window -v
tmux send-keys 'rosrun e2e_handover position'
tmux split-window -v -t 0
#tmux send-keys ''
tmux select-pane -t 0
tmux attach-session -d -t $session

