
model_directory: '../../../models'

num_epochs: 100
batch_size: 32
learning_rate: 0.001
num_workers: 4
log_step: 10 # step size for printing log info
frame_skip: 1 # will train only on every nth frame
test_fraction: 0.2

use_rgb_1: False
use_rgb_2: True
use_depth_1: False
use_depth_2: False
use_tactile: False
use_force_torque: True
use_segmentation: False
use_lstm: True
lstm_sequence_length: 5

output_velocity: False