
model_directory: '../../../models'

num_epochs: 100
batch_size: 32
learning_rate: 0.001
num_workers: 4
log_step: 10 # step size for printing log info

use_camera_1: True
use_camera_2: False
use_segmentation: False
use_depth: False
use_tactile: False
use_force_torque: True